-- MySQL Script generated by MySQL Workbench
-- Sun 03 Aug 2014 10:50:21 PM CEST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema streep
-- -----------------------------------------------------
-- Contains the models for the streep application
CREATE SCHEMA IF NOT EXISTS `streep` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `streep` ;

-- -----------------------------------------------------
-- Table `streep`.`camera_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streep`.`camera_position` (
  `id` INT NULL AUTO_INCREMENT,
  `x` INT NULL DEFAULT 0,
  `y` INT NULL DEFAULT 0,
  `z` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'Contains the XYZ';


-- -----------------------------------------------------
-- Table `streep`.`camera_lookat_position`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streep`.`camera_lookat_position` (
  `x` INT NULL,
  `y` INT NULL,
  `z` INT NULL,
  `id` INT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `streep`.`perspective`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streep`.`perspective` (
  `id` INT NULL AUTO_INCREMENT,
  `camera_position` INT NULL,
  `camera_lookat_position` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_perspective_camera_position_idx` (`id` ASC, `camera_position` ASC),
  INDEX `fk_perspective_lookat_position_idx` (`camera_position` ASC, `camera_lookat_position` ASC),
  CONSTRAINT `fk_perspective_camera_position`
    FOREIGN KEY (`id` , `camera_position`)
    REFERENCES `streep`.`camera_position` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_perspective_lookat_position`
    FOREIGN KEY (`camera_position` , `camera_lookat_position`)
    REFERENCES `streep`.`camera_lookat_position` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Describes a viewpoint for the application, camera-location, camera focus position, lightposition';


-- -----------------------------------------------------
-- Table `streep`.`component`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `streep`.`component` (
  `id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `desc_short` TEXT NULL,
  `desc_long` TEXT NULL,
  `focus_perspective` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_component_perspective_idx` (`focus_perspective` ASC),
  CONSTRAINT `fk_component_perspective`
    FOREIGN KEY (`focus_perspective`)
    REFERENCES `streep`.`perspective` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
